// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "SWC1001:XmlDocumentationCommentShouldBeSpelledCorrectly", MessageId = "Polyline", Justification = "Matches System.Windows.Shapes.Polyline.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DynamicSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.ICategoryAxisInformationProvider.GetCategories(Microsoft.Windows.Controls.DataVisualization.Charting.ICategoryAxis)", Justification = "No reason to expose these methods.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DynamicSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetRange(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)", Justification = "No reason to expose these methods.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DynamicSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetSmallestValueDelta(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)", Justification = "No reason to expose these methods.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.ActualMaximum")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.ActualMinimum")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.GetPlotAreaCoordinate(System.IComparable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.Update(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider,Microsoft.Windows.Controls.DataVisualization.Range`1<System.IComparable>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DynamicSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetActualRange(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DynamicSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetDesiredRange(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.HybridAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxisGridLinesElementProvider.GridLinesElement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.HybridAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxisGridLinesElementProvider.GridLinesElementPropertyChanged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.HybridAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxisGridLinesElementProvider.GridLinesElementPropertyChanged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.GetPlotAreaCoordinateValueRange(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.HybridAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxisGridLinesElementProvider.GridLinesElementChanged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DataPointSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.ICategoryAxisInformationProvider.GetCategories(Microsoft.Windows.Controls.DataVisualization.Charting.ICategoryAxis)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DataPointSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetActualRange(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.DataPointSeriesWithAxes.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxisInformationProvider.GetDesiredRange(Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.Axis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxis.Register(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.Axis.#Microsoft.Windows.Controls.DataVisualization.Charting.IAxis.Unregister(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Windows.Controls.DataVisualization.Charting.RangeAxis.#Microsoft.Windows.Controls.DataVisualization.Charting.IRangeAxis.Range")]
