'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace SamlIdPInitiated.ServiceProvider


	''' <summary>
	''' UserLogin class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class UserLogin

		''' <summary>
		''' Head2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Head2 As Global.System.Web.UI.HtmlControls.HtmlHead

		''' <summary>
		''' myform control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected myform As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' txtUserName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txtUserName As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' txtPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txtPassword As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' lblErrorMessage control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblErrorMessage As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' btnLogin control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnLogin As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
