<?xml version="1.0" encoding="utf-8"?><Database Name="ReportTestDB" Class="ReportTestDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ATIK-PC;Initial Catalog=ReportTestDB;Integrated Security=True" SettingsObjectName="WPFReportTest.Properties.Settings" SettingsPropertyName="ReportTestDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EMPLOYEE_INFO" Member="EMPLOYEE_INFOs">
    <Type Name="EMPLOYEE_INFO">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>