//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Illusion.PurchasingsEDM
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IllusionPurchasingDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IllusionPurchasingDBEntities object using the connection string found in the 'IllusionPurchasingDBEntities' section of the application configuration file.
        /// </summary>
        public IllusionPurchasingDBEntities() : base("name=IllusionPurchasingDBEntities", "IllusionPurchasingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IllusionPurchasingDBEntities object.
        /// </summary>
        public IllusionPurchasingDBEntities(string connectionString) : base(connectionString, "IllusionPurchasingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IllusionPurchasingDBEntities object.
        /// </summary>
        public IllusionPurchasingDBEntities(EntityConnection connection) : base(connection, "IllusionPurchasingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductVendor> ProductVendors
        {
            get
            {
                if ((_ProductVendors == null))
                {
                    _ProductVendors = base.CreateObjectSet<ProductVendor>("ProductVendors");
                }
                return _ProductVendors;
            }
        }
        private ObjectSet<ProductVendor> _ProductVendors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PurchaseOrder> PurchaseOrders
        {
            get
            {
                if ((_PurchaseOrders == null))
                {
                    _PurchaseOrders = base.CreateObjectSet<PurchaseOrder>("PurchaseOrders");
                }
                return _PurchaseOrders;
            }
        }
        private ObjectSet<PurchaseOrder> _PurchaseOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vendor> Vendors
        {
            get
            {
                if ((_Vendors == null))
                {
                    _Vendors = base.CreateObjectSet<Vendor>("Vendors");
                }
                return _Vendors;
            }
        }
        private ObjectSet<Vendor> _Vendors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VendorContact> VendorContacts
        {
            get
            {
                if ((_VendorContacts == null))
                {
                    _VendorContacts = base.CreateObjectSet<VendorContact>("VendorContacts");
                }
                return _VendorContacts;
            }
        }
        private ObjectSet<VendorContact> _VendorContacts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductVendors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductVendors(ProductVendor productVendor)
        {
            base.AddObject("ProductVendors", productVendor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PurchaseOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPurchaseOrders(PurchaseOrder purchaseOrder)
        {
            base.AddObject("PurchaseOrders", purchaseOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vendors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendors(Vendor vendor)
        {
            base.AddObject("Vendors", vendor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VendorContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendorContacts(VendorContact vendorContact)
        {
            base.AddObject("VendorContacts", vendorContact);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IllusionPurchasingDBModel", Name="ProductVendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductVendor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductVendor object.
        /// </summary>
        /// <param name="productVendorID">Initial value of the ProductVendorID property.</param>
        public static ProductVendor CreateProductVendor(global::System.Int32 productVendorID)
        {
            ProductVendor productVendor = new ProductVendor();
            productVendor.ProductVendorID = productVendorID;
            return productVendor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductVendorID
        {
            get
            {
                return _ProductVendorID;
            }
            set
            {
                if (_ProductVendorID != value)
                {
                    OnProductVendorIDChanging(value);
                    ReportPropertyChanging("ProductVendorID");
                    _ProductVendorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductVendorID");
                    OnProductVendorIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductVendorID;
        partial void OnProductVendorIDChanging(global::System.Int32 value);
        partial void OnProductVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNumber
        {
            get
            {
                return _ProductNumber;
            }
            set
            {
                OnProductNumberChanging(value);
                ReportPropertyChanging("ProductNumber");
                _ProductNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNumber");
                OnProductNumberChanged();
            }
        }
        private global::System.String _ProductNumber;
        partial void OnProductNumberChanging(global::System.String value);
        partial void OnProductNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.String _Vendor;
        partial void OnVendorChanging(global::System.String value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LastReceiptCost
        {
            get
            {
                return _LastReceiptCost;
            }
            set
            {
                OnLastReceiptCostChanging(value);
                ReportPropertyChanging("LastReceiptCost");
                _LastReceiptCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastReceiptCost");
                OnLastReceiptCostChanged();
            }
        }
        private Nullable<global::System.Decimal> _LastReceiptCost;
        partial void OnLastReceiptCostChanging(Nullable<global::System.Decimal> value);
        partial void OnLastReceiptCostChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IllusionPurchasingDBModel", Name="PurchaseOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PurchaseOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PurchaseOrder object.
        /// </summary>
        /// <param name="purchaseOrderID">Initial value of the PurchaseOrderID property.</param>
        public static PurchaseOrder CreatePurchaseOrder(global::System.Int32 purchaseOrderID)
        {
            PurchaseOrder purchaseOrder = new PurchaseOrder();
            purchaseOrder.PurchaseOrderID = purchaseOrderID;
            return purchaseOrder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PurchaseOrderID
        {
            get
            {
                return _PurchaseOrderID;
            }
            set
            {
                if (_PurchaseOrderID != value)
                {
                    OnPurchaseOrderIDChanging(value);
                    ReportPropertyChanging("PurchaseOrderID");
                    _PurchaseOrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PurchaseOrderID");
                    OnPurchaseOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _PurchaseOrderID;
        partial void OnPurchaseOrderIDChanging(global::System.Int32 value);
        partial void OnPurchaseOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.String _Vendor;
        partial void OnVendorChanging(global::System.String value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total_Purchase
        {
            get
            {
                return _Total_Purchase;
            }
            set
            {
                OnTotal_PurchaseChanging(value);
                ReportPropertyChanging("Total_Purchase");
                _Total_Purchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Purchase");
                OnTotal_PurchaseChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total_Purchase;
        partial void OnTotal_PurchaseChanging(Nullable<global::System.Decimal> value);
        partial void OnTotal_PurchaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Average_Purchase
        {
            get
            {
                return _Average_Purchase;
            }
            set
            {
                OnAverage_PurchaseChanging(value);
                ReportPropertyChanging("Average_Purchase");
                _Average_Purchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Average_Purchase");
                OnAverage_PurchaseChanged();
            }
        }
        private Nullable<global::System.Decimal> _Average_Purchase;
        partial void OnAverage_PurchaseChanging(Nullable<global::System.Decimal> value);
        partial void OnAverage_PurchaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Minimum_Purchase
        {
            get
            {
                return _Minimum_Purchase;
            }
            set
            {
                OnMinimum_PurchaseChanging(value);
                ReportPropertyChanging("Minimum_Purchase");
                _Minimum_Purchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Minimum_Purchase");
                OnMinimum_PurchaseChanged();
            }
        }
        private Nullable<global::System.Decimal> _Minimum_Purchase;
        partial void OnMinimum_PurchaseChanging(Nullable<global::System.Decimal> value);
        partial void OnMinimum_PurchaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Maximum_Purchase
        {
            get
            {
                return _Maximum_Purchase;
            }
            set
            {
                OnMaximum_PurchaseChanging(value);
                ReportPropertyChanging("Maximum_Purchase");
                _Maximum_Purchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Maximum_Purchase");
                OnMaximum_PurchaseChanged();
            }
        }
        private Nullable<global::System.Decimal> _Maximum_Purchase;
        partial void OnMaximum_PurchaseChanging(Nullable<global::System.Decimal> value);
        partial void OnMaximum_PurchaseChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IllusionPurchasingDBModel", Name="Vendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendor object.
        /// </summary>
        /// <param name="vendorID">Initial value of the VendorID property.</param>
        public static Vendor CreateVendor(global::System.Int32 vendorID)
        {
            Vendor vendor = new Vendor();
            vendor.VendorID = vendorID;
            return vendor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                if (_VendorID != value)
                {
                    OnVendorIDChanging(value);
                    ReportPropertyChanging("VendorID");
                    _VendorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VendorID");
                    OnVendorIDChanged();
                }
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vendor1
        {
            get
            {
                return _Vendor1;
            }
            set
            {
                OnVendor1Changing(value);
                ReportPropertyChanging("Vendor1");
                _Vendor1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vendor1");
                OnVendor1Changed();
            }
        }
        private global::System.String _Vendor1;
        partial void OnVendor1Changing(global::System.String value);
        partial void OnVendor1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine1
        {
            get
            {
                return _AddressLine1;
            }
            set
            {
                OnAddressLine1Changing(value);
                ReportPropertyChanging("AddressLine1");
                _AddressLine1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressLine1");
                OnAddressLine1Changed();
            }
        }
        private global::System.String _AddressLine1;
        partial void OnAddressLine1Changing(global::System.String value);
        partial void OnAddressLine1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine2
        {
            get
            {
                return _AddressLine2;
            }
            set
            {
                OnAddressLine2Changing(value);
                ReportPropertyChanging("AddressLine2");
                _AddressLine2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressLine2");
                OnAddressLine2Changed();
            }
        }
        private global::System.String _AddressLine2;
        partial void OnAddressLine2Changing(global::System.String value);
        partial void OnAddressLine2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IllusionPurchasingDBModel", Name="VendorContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VendorContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VendorContact object.
        /// </summary>
        /// <param name="vendorContactID">Initial value of the VendorContactID property.</param>
        public static VendorContact CreateVendorContact(global::System.Int32 vendorContactID)
        {
            VendorContact vendorContact = new VendorContact();
            vendorContact.VendorContactID = vendorContactID;
            return vendorContact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorContactID
        {
            get
            {
                return _VendorContactID;
            }
            set
            {
                if (_VendorContactID != value)
                {
                    OnVendorContactIDChanging(value);
                    ReportPropertyChanging("VendorContactID");
                    _VendorContactID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VendorContactID");
                    OnVendorContactIDChanged();
                }
            }
        }
        private global::System.Int32 _VendorContactID;
        partial void OnVendorContactIDChanging(global::System.Int32 value);
        partial void OnVendorContactIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.String _Vendor;
        partial void OnVendorChanging(global::System.String value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion

    
    }

    #endregion

    
}
