//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Consulting.WorkflowStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Consulting.WorkflowStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow aborted.
        /// </summary>
        public static string AbortedInDebugStatus {
            get {
                return ResourceManager.GetString("AbortedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow aborted.
        /// </summary>
        public static string AbortedStatus {
            get {
                return ResourceManager.GetString("AbortedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow aborting ....
        /// </summary>
        public static string AbortingInDebugStatus {
            get {
                return ResourceManager.GetString("AbortingInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow aborting ....
        /// </summary>
        public static string AbortingServiceHostStatus {
            get {
                return ResourceManager.GetString("AbortingServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow aborting ....
        /// </summary>
        public static string AbortingStatus {
            get {
                return ResourceManager.GetString("AbortingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Studio
        ///Copyright (c) Microsoft Corporation. All rights reserved.
        ///Version {0}.
        /// </summary>
        public static string AboutDialogMessage {
            get {
                return ResourceManager.GetString("AboutDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host closed.
        /// </summary>
        public static string ClosedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host closed.
        /// </summary>
        public static string ClosedServiceHostStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string CollectionCategoryToToolbox {
            get {
                return ResourceManager.GetString("CollectionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow completed with completion state {0}.
        /// </summary>
        public static string CompletedInDebugStatus {
            get {
                return ResourceManager.GetString("CompletedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow completed with completion state {0}.
        /// </summary>
        public static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workflow is running. Do you wish to exit?.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are one or more running workflows. Do you wish to close?.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}.
        /// </summary>
        public static string ConfirmSaveDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ConfirmSaveDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Flow.
        /// </summary>
        public static string ControlFlowCategoryToToolbox {
            get {
                return ResourceManager.GetString("ControlFlowCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging workflow ....
        /// </summary>
        public static string DebuggingStatus {
            get {
                return ResourceManager.GetString("DebuggingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug.
        /// </summary>
        public static string DebugMenu {
            get {
                return ResourceManager.GetString("DebugMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string DebugMenuAbort {
            get {
                return ResourceManager.GetString("DebugMenuAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Debugging.
        /// </summary>
        public static string DebugMenuStartDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;F5&apos;.
        /// </summary>
        public static string DebugMenuStartDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DebugMenuStartDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Without Debugging.
        /// </summary>
        public static string DebugMenuStartWithoutDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;F5&apos;.
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogCaptionError {
            get {
                return ResourceManager.GetString("DialogCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        public static string ErrorHandlingCategoryToToolbox {
            get {
                return ResourceManager.GetString("ErrorHandlingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred loading document
        ///
        ///{0}.
        /// </summary>
        public static string ErrorLoadingDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorLoadingDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred loading document
        ///
        ///{0}.
        /// </summary>
        public static string ErrorLoadingInDebugDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorLoadingInDebugDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred running workflow
        ///
        ///{0}.
        /// </summary>
        public static string ErrorRunningDialogMessage {
            get {
                return ResourceManager.GetString("ErrorRunningDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorRunningDialogTitle {
            get {
                return ResourceManager.GetString("ErrorRunningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorValidationItem {
            get {
                return ResourceManager.GetString("ErrorValidationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionServiceHostStatus {
            get {
                return ResourceManager.GetString("ExceptionServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionStatus {
            get {
                return ResourceManager.GetString("ExceptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionWhenRunningInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionWhenRunningInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host faulted.
        /// </summary>
        public static string FaultedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host faulted.
        /// </summary>
        public static string FaultedServiceHostStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reference ....
        /// </summary>
        public static string FileMenuAddReference {
            get {
                return ResourceManager.GetString("FileMenuAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string FileMenuCloseAll {
            get {
                return ResourceManager.GetString("FileMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileMenuExit {
            get {
                return ResourceManager.GetString("FileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service ....
        /// </summary>
        public static string FileMenuNewService {
            get {
                return ResourceManager.GetString("FileMenuNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workflow ....
        /// </summary>
        public static string FileMenuNewWorkflow {
            get {
                return ResourceManager.GetString("FileMenuNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ....
        /// </summary>
        public static string FileMenuOpen {
            get {
                return ResourceManager.GetString("FileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileMenuSave {
            get {
                return ResourceManager.GetString("FileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string FileMenuSaveAll {
            get {
                return ResourceManager.GetString("FileMenuSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string FileMenuSaveAs {
            get {
                return ResourceManager.GetString("FileMenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        public static string FlowchartCategoryToToolbox {
            get {
                return ResourceManager.GetString("FlowchartCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpMenuAbout {
            get {
                return ResourceManager.GetString("HelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Studio.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string MessagingCategoryToToolbox {
            get {
                return ResourceManager.GetString("MessagingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New workflow {0}.
        /// </summary>
        public static string NewWorkflowTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New workflow {0} {1}.
        /// </summary>
        public static string NewWorkflowWithModifierTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowWithModifierTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host opened.
        /// </summary>
        public static string OpenServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow service host opened.
        /// </summary>
        public static string OpenServiceHostStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitives.
        /// </summary>
        public static string PrimitivesCategoryToToolbox {
            get {
                return ResourceManager.GetString("PrimitivesCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow running ....
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string RuntimeCategoryToToolbox {
            get {
                return ResourceManager.GetString("RuntimeCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to following workflows?
        ///{0}.
        /// </summary>
        public static string SaveChangesDialogMessage {
            get {
                return ResourceManager.GetString("SaveChangesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChangesDialogTitle {
            get {
                return ResourceManager.GetString("SaveChangesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        public static string SaveSuccessfulStatus {
            get {
                return ResourceManager.GetString("SaveSuccessfulStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving workflow ....
        /// </summary>
        public static string SavingStatus {
            get {
                return ResourceManager.GetString("SavingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TransactionCategoryToToolbox {
            get {
                return ResourceManager.GetString("TransactionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred, see log for details : {0}.
        /// </summary>
        public static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred on {0} : {1}.
        /// </summary>
        public static string UnhandledExceptionTrace {
            get {
                return ResourceManager.GetString("UnhandledExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string ViewMenuDebug {
            get {
                return ResourceManager.GetString("ViewMenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ViewMenuErrors {
            get {
                return ResourceManager.GetString("ViewMenuErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string ViewMenuOutline {
            get {
                return ResourceManager.GetString("ViewMenuOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ViewMenuOutput {
            get {
                return ResourceManager.GetString("ViewMenuOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ViewMenuProperties {
            get {
                return ResourceManager.GetString("ViewMenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string ViewMenuToolbox {
            get {
                return ResourceManager.GetString("ViewMenuToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningValidationItem {
            get {
                return ResourceManager.GetString("WarningValidationItem", resourceCulture);
            }
        }
    }
}
