'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UiManagerOutlookAddIn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property espressoCup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("espressoCup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property espressoCup_tall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("espressoCup_tall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SimpleFormRegionOfs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SimpleFormRegionOfs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        '''  &lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        '''  &lt;formRegionName&gt;UIM&lt;/formRegionName&gt;
        '''  &lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        '''  &lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        '''  &lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        '''  &lt;icons&gt;
        '''    &lt;page&gt;addin&lt;/page&gt;
        '''  &lt;/icons&gt;
        '''&lt;/FormRegion&gt;.
        '''</summary>
        Friend ReadOnly Property SimpleFormRegionXml() As String
            Get
                Return ResourceManager.GetString("SimpleFormRegionXml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        '''          onLoad=&quot;OnLoad&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        '''			&lt;group id=&quot;uimGroup&quot; label=&quot;UI Manager&quot;&gt;
        '''				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        '''							  label=&quot;TaskPane&quot;
        '''							  imageMso=&quot;ControlLayoutStacked&quot;
        '''							  size=&quot;large&quot;
        '''							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        '''			&lt;/group&gt;
        '''		&lt;/tab&gt;
        '''    &lt;/tabs&gt;
        '''  &lt;/ribbon&gt;
        '''&lt;/customUI&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property SimpleRibbon() As String
            Get
                Return ResourceManager.GetString("SimpleRibbon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        '''          onLoad=&quot;OnLoad&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        '''			&lt;group id=&quot;uimGroup&quot; label=&quot;UI Manager&quot;&gt;
        '''				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        '''							  label=&quot;TaskPane&quot;
        '''							  imageMso=&quot;ControlLayoutStacked&quot;
        '''							  size=&quot;large&quot;
        '''							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        '''			&lt;/group&gt;
        '''			&lt;group id=&quot;mailServiceGroup&quot;
        '''				   label=&quot;Add-in Services&quot;
        '''				   getVisible=&quot;GetVisible&quot;&gt;
        '''				&lt;button id=&quot;sendList&quot;
        '''					 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TaskRibbon() As String
            Get
                Return ResourceManager.GetString("TaskRibbon", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
