using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace WpfEfDAL
{
    public partial class Customer : IDataErrorInfo
    {
        public Customer()
        {
            // Set defaults
            this.LastName = "[new]";
        }

    /// <summary>
    //  This method is called in the LastName property setter of the customer
    //  partial class generated by the Entity Data Model designer.
    /// </summary>
        partial void OnLastNameChanged()
        {
            //Perform validation.
            if ((_LastName == null) || (_LastName.Trim() == "") || (_LastName.Trim() == "[new]"))
                this.AddError("LastName", "Please enter a last name.");
            else
                this.RemoveError("LastName");
        }

#region "IDataErrorInfo Members"

        private Dictionary<String, String> m_validationErrors = new Dictionary<String, String>();

        private void AddError(String columnName, String msg)
        {
            if (!m_validationErrors.ContainsKey(columnName))
                m_validationErrors.Add(columnName, msg);
        }

        private void RemoveError(String columnName)
        {
            if (m_validationErrors.ContainsKey(columnName))
                m_validationErrors.Remove(columnName);
        }

        public Boolean HasErrors
        {
            get
            {
                return m_validationErrors.Count > 0;
            }
        }

        public string Error
        {
            get
            {
                if (m_validationErrors.Count > 0)
                    return "Customer data is invalid";
                else
                    return null;
            }
        }

        public string this[string columnName]
        {
            get
            {
                if (m_validationErrors.ContainsKey(columnName))
                    return m_validationErrors[columnName].ToString();
                else
                    return null;
            }
        }

#endregion

    
    }
}
